### ISSUE TITLE
from_me?がundefinedといって落ちました

### ISSUE THREAD

**Issue by Na0ki** [toshia/ahiruyaki#5]
タイトルの通りです。
私の環境では頻度は少ないですが、何回か再現されています。
とりあえず落ちた時のログをはっつけます。

OS: OSX El Capitan
mikutter: 3.5-develop
ruby: 2.3.1

```
/Users/ahiru/.mikutter/plugin/ahiruyaki/ahiruyaki.rb:145:in `block (3 levels) in <top (required)>': undefined method `from_me?' for nil:NilClass
Did you mean?  frozen?
     from /Users/ahiru/.mikutter/plugin/ahiruyaki/ahiruyaki.rb:148:in `yield'
     from /Users/ahiru/.mikutter/plugin/ahiruyaki/ahiruyaki.rb:148:in `yield'
     from /Users/ahiru/.mikutter/plugin/ahiruyaki/ahiruyaki.rb:148:in `yield'
     from /Users/ahiru/.mikutter/plugin/ahiruyaki/ahiruyaki.rb:148:in `each'
     from /Users/ahiru/.mikutter/plugin/ahiruyaki/ahiruyaki.rb:148:in `each'
     from /Users/ahiru/.mikutter/plugin/ahiruyaki/ahiruyaki.rb:148:in `each'
     from /Users/ahiru/.mikutter/plugin/ahiruyaki/ahiruyaki.rb:148:in `each'
     from /Users/ahiru/.mikutter/plugin/ahiruyaki/ahiruyaki.rb:148:in `each'
     from /Users/ahiru/.mikutter/plugin/ahiruyaki/ahiruyaki.rb:148:in `each'
     from /Users/ahiru/.mikutter/plugin/ahiruyaki/ahiruyaki.rb:148:in `each'
     from /Users/ahiru/.mikutter/plugin/ahiruyaki/ahiruyaki.rb:148:in `each'
     from /Users/ahiru/.mikutter/plugin/ahiruyaki/ahiruyaki.rb:148:in `each'
     from /Users/ahiru/.mikutter/plugin/ahiruyaki/ahiruyaki.rb:148:in `each'
     from /Users/ahiru/.mikutter/plugin/ahiruyaki/ahiruyaki.rb:148:in `each'
     from /Users/ahiru/.mikutter/plugin/ahiruyaki/ahiruyaki.rb:148:in `each'
     from /Users/ahiru/.mikutter/plugin/ahiruyaki/ahiruyaki.rb:148:in `block (2 levels) in <top (required)>'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/listener.rb:25:in `call'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:97:in `block (2 levels) in call_all_listeners'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:96:in `each'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:96:in `block in call_all_listeners'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:95:in `catch'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:95:in `call_all_listeners'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:45:in `block (2 levels) in call'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer/procedure.rb:24:in `run'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer/extend.rb:58:in `run_once'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer/extend.rb:30:in `run'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer.rb:43:in `method_missing'
     from /Users/ahiru/mikutter/source/core/plugin/gtk/delayer.rb:10:in `block in boot'
     from /Users/ahiru/mikutter/source/core/plugin/gtk/mainloop.rb:10:in `main'
     from /Users/ahiru/mikutter/source/core/plugin/gtk/mainloop.rb:10:in `mainloop'
     from mikutter.rb:63:in `boot!'
     from mikutter.rb:92:in `<main>'
notice: mikutter.rb:69:in `rescue in boot!': catch exception `SystemExit'
notice: mikutter.rb:71:in `rescue in boot!': => `SystemExit'
notice: mikutter.rb:96:in `rescue in <main>': catch SystemExit
notice: mikutter.rb:80:in `error_handling!': catch NoMethodError
/Users/ahiru/.mikutter/plugin/ahiruyaki/ahiruyaki.rb:148:in `yield': undefined method `from_me?' for nil:NilClass (NoMethodError)
Did you mean?  frozen?
    from /Users/ahiru/.mikutter/plugin/ahiruyaki/ahiruyaki.rb:148:in `yield'
    from /Users/ahiru/.mikutter/plugin/ahiruyaki/ahiruyaki.rb:148:in `yield'
    from /Users/ahiru/.mikutter/plugin/ahiruyaki/ahiruyaki.rb:148:in `each'
    from /Users/ahiru/.mikutter/plugin/ahiruyaki/ahiruyaki.rb:148:in `each'
    from /Users/ahiru/.mikutter/plugin/ahiruyaki/ahiruyaki.rb:148:in `each'
    from /Users/ahiru/.mikutter/plugin/ahiruyaki/ahiruyaki.rb:148:in `each'
    from /Users/ahiru/.mikutter/plugin/ahiruyaki/ahiruyaki.rb:148:in `each'
    from /Users/ahiru/.mikutter/plugin/ahiruyaki/ahiruyaki.rb:148:in `each'
    from /Users/ahiru/.mikutter/plugin/ahiruyaki/ahiruyaki.rb:148:in `each'
    from /Users/ahiru/.mikutter/plugin/ahiruyaki/ahiruyaki.rb:148:in `each'
    from /Users/ahiru/.mikutter/plugin/ahiruyaki/ahiruyaki.rb:148:in `each'
    from /Users/ahiru/.mikutter/plugin/ahiruyaki/ahiruyaki.rb:148:in `each'
    from /Users/ahiru/.mikutter/plugin/ahiruyaki/ahiruyaki.rb:148:in `each'
    from /Users/ahiru/.mikutter/plugin/ahiruyaki/ahiruyaki.rb:148:in `each'
    from /Users/ahiru/.mikutter/plugin/ahiruyaki/ahiruyaki.rb:148:in `block (2 levels) in <top (required)>'
    from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/listener.rb:25:in `call'
    from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:97:in `block (2 levels) in call_all_listeners'
    from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:96:in `each'
    from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:96:in `block in call_all_listeners'
    from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:95:in `catch'
    from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:95:in `call_all_listeners'
    from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:45:in `block (2 levels) in call'
    from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer/procedure.rb:24:in `run'
    from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer/extend.rb:58:in `run_once'
    from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer/extend.rb:30:in `run'
    from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer.rb:43:in `method_missing'
    from /Users/ahiru/mikutter/source/core/plugin/gtk/delayer.rb:10:in `block in boot'
    from /Users/ahiru/mikutter/source/core/plugin/gtk/mainloop.rb:10:in `main'
    from /Users/ahiru/mikutter/source/core/plugin/gtk/mainloop.rb:10:in `mainloop'
    from mikutter.rb:63:in `boot!'
    from mikutter.rb:92:in `<main>'
```

**Comment by Na0ki** [comment]
#8 で対応しました
